### ISSUE TITLE
Roll-forward end to end

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#6420]
* [x] SDK support - add a project property to set roll forward in the runtime config
* [x] COM server projects should set this to `LatestMinor` by default - see #5062 
* [x] Consider modifying the default to `LatestMinor` for the "component" projects as well
* [x] Merging behavior for inner framework references - see #5870 
* [x] tracking - use `LatestPatch` for `Microsoft.AspNetCore.App` https://github.com/aspnet/AspNetCore/issues/10567
* [x] tracking - use `LatestPatch` for `Microsoft.WindowsDesktop.App` https://github.com/dotnet/core-setup/issues/6552
* [x] Validate that the roll forward for components (and for COM servers) works as expected by default - ideally with a sample for component hosting

**Comment by vitek-karas** [comment]
SDK support implementation in PR dotnet/sdk#3296

**Comment by vitek-karas** [comment]
Implemented the merging behavior changes in PR #6569

**Comment by vitek-karas** [comment]
`Microsoft.WindowsDesktop.App` switched to `LatestPatch` in #6664

**Comment by vitek-karas** [comment]
SDK now supports `<RollForward>` msbuild property which propagates its value to the `.runtimeconfig.json` - dotnet/sdk#3296

**Comment by vitek-karas** [comment]
ASP.NET framework is now using `LatestPatch` as well - https://github.com/aspnet/AspNetCore/pull/11150

**Comment by vitek-karas** [comment]
Using `LatestMinor` for both COM server and components has been enabled by default in https://github.com/dotnet/sdk/pull/3305/files.

**Comment by vitek-karas** [comment]
I adapted the hostfxr sample to load two separate components with different version requirements and it worked exactly as designed - no matter the other the components did load successfully.
