### ISSUE TITLE
Component dependency resolution on self-contained apps

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/core-setup#6961]
This issue is meant to track all the work necessary to make component dependency resolution work well on self-contained apps. That is a component is dynamically loaded into a host which is a self-contained app. This relates specifically to the usage of `AssemblyDependencyResolver`, so app which provide their own dependency resolution mechanism for components are not affected.

On the other hand all these scenarios are affected:
* Managed plugins using `AssemblyDependencyResolver` (which is our recommendation)
* Managed COM servers
* Managed components loaded through native hosting APIs

* [ ] - Framework assembly overrides - #6826 
  * [ ] - SDK change to include information about framework assemblies in self-contained apps - dotnet/sdk#3339
  * [ ] - Implementation relying on the new SDK functionality in `hostpolicy`
  * [ ] - Validation
* [ ] - RID specific asset resolution - #6960 
  * [ ] - SDK change to include RID fallback graph in self-contained apps
  * [ ] - Tests in core-setup (the functionality should automatically light up with the SDK change)
  * [ ] - Validation
